version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing source NPM dependencies...
      - npm install

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 010928211649.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t ecr-repo-for-npm-app .

  post_build:
    commands:
      - echo Tagging the Docker image...
      - docker tag ecr-repo-for-npm-app:latest 010928211649.dkr.ecr.us-east-1.amazonaws.com/aws-ecs-docker:latest
      - echo Pushing the Docker image to ECR...
      - docker push 010928211649.dkr.ecr.us-east-1.amazonaws.com/aws-ecs-docker:latest

artifacts:
  files:
    - '**/*'
